#! /bin/bash
# Copyright (C) 2019-2021  Marcus Rickert
#
# See https://github.com/marcus67/snap-little-brother
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

mkdir -p $SNAP_USER_DATA/spool
export Persistence__sqlite_dir=$SNAP_USER_DATA/spool
export NO_SELENIUM_TESTS=1
export STATUS_SERVER_PORT=${STATUS_SERVER_PORT:-5562}
export PROMETHEUS_SERVER_PORT=${PROMETHEUS_SERVER_PORT:-8890}
$SNAP/bin/run_little_brother_test_suite.py
