# Copyright (C) 2019-2021  Marcus Rickert
#
# See https://github.com/marcus67/snap-little-brother
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

name: little-brother-slave
base: core20
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Tool to monitor login times and terminate process if usage times are exceeded
description: |
  Tool to monitor login times and terminate process if usage times are exceeded

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  configuration:
    plugin: dump
    source: .
    organize:
      little-brother.config: etc/

  python-app:
    # See 'snapcraft plugins'
    plugin: python
    build-environment:
      # See https://forum.snapcraft.io/t/error-invalid-command-bdist-wheel/18960/2
      - PYTHONPATH: "$SNAPCRAFT_PART_INSTALL/usr/lib/python3/dist-packages"
    source: .
    build-packages:
      - python3-dev
      - libsasl2-dev
      - libldap2-dev
      - libssl-dev
      - python3-wheel

    stage-packages:
      - mpg123
      - sudo
      - python3-dev
      - libsasl2-dev
      - libldap2-dev
      - libssl-dev
      - python3-wheel

    python-packages:
      - http://192.168.1.3:8080/dist/little-brother-0.4.10.tar.gz
      - http://192.168.1.3:8080/contrib/python_base_app/dist/python-base-app-0.2.26.tar.gz
      - some-flask-helpers

apps:
  test-wrapper-app:
    command: run-little-brother-test-suite
    plugs: [process-control]
  wrapper-app:
    command: run-little-brother
    daemon: simple
    restart-condition: always
    plugs: [process-control]
